# generated by running rails generate migration AddNumberOfPagesToBooks number_of_pages:integer
class AddNumberOfPagesToBooks < ActiveRecord::Migration
  def change
    add_column :books, :number_of_pages, :integer
  end
end
