# generated by running rails generate migration AddNumberOfPagesToBooks number_of_pages:decimal
class AddNumberOfPagesToBooks < ActiveRecord::Migration
  def change
    add_column :books, :number_of_pages, :decimal
  end
end
